import os


class MLConfig:
    BASE_DIR = os.path.dirname(os.path.abspath(__file__))
    MODEL_PATH = os.path.join(BASE_DIR, "models", "best_mobilenet_model.keras")
    IMG_SIZE = 224
    CONSTELLATIONS = [
        ("Andromeda", "And", "Andromeda"),
        ("Antlia", "Ant", "Pompa (Wodna)"),
        ("Apus", "Aps", "Rajski Ptak"),
        ("Aquarius", "Aqr", "Wodnik"),
        ("Aquila", "Aql", "Orzeł"),
        ("Ara", "Ara", "Ołtarz"),
        ("Aries", "Ari", "Baran"),
        ("Auriga", "Aur", "Woźnica"),
        ("Bootes", "Boo", "Wolarz"),
        ("Caelum", "Cae", "Rylec"),
        ("Camelopardalis", "Cam", "Żyrafa"),
        ("Cancer", "Cnc", "Rak"),
        ("Canes Venatici", "CVn", "Psy Gończe"),
        ("Canis Maior", "CMa", "Wielki Pies"),
        ("Canis Minor", "CMi", "Mały Pies"),
        ("Capricornus", "Cap", "Koziorożec"),
        ("Carina", "Car", "Kil"),
        ("Cassiopeia", "Cas", "Kasjopea"),
        ("Centaurus", "Cen", "Centaur"),
        ("Cepheus", "Cep", "Cefeusz"),
        ("Cetus", "Cet", "Wieloryb"),
        ("Chamaeleon", "Cha", "Kameleon"),
        ("Circinus", "Cir", "Cyrkiel"),
        ("Columba", "Col", "Gołąb"),
        ("Coma Berenices", "Com", "Warkocz Bereniki"),
        ("Corona Australis", "CrA", "Korona Południowa"),
        ("Corona Borealis", "CrB", "Korona Północna"),
        ("Corvus", "Crv", "Kruk"),
        ("Crater", "Crt", "Puchar"),
        ("Crux", "Cru", "Krzyż (Południa)"),
        ("Cygnus", "Cyg", "Łabędź"),
        ("Delphinus", "Del", "Delfin"),
        ("Dorado", "Dor", "Złota Ryba"),
        ("Draco", "Dra", "Smok"),
        ("Equuleus", "Equ", "Źrebię (Mały Koń)"),
        ("Eridanus", "Eri", "Erydan"),
        ("Fornax", "For", "Piec"),
        ("Gemini", "Gem", "Bliźnięta"),
        ("Grus", "Gru", "Żuraw"),
        ("Hercules", "Her", "Herkules"),
        ("Horologium", "Hor", "Zegar"),
        ("Hydra", "Hya", "Hydra"),
        ("Hydrus", "Hyi", "Wąż Wodny"),
        ("Indus", "Ind", "Indianin"),
        ("Lacerta", "Lac", "Jaszczurka"),
        ("Leo", "Leo", "Lew"),
        ("Leo Minor", "LMi", "Mały Lew"),
        ("Lepus", "Lep", "Zając"),
        ("Libra", "Lib", "Waga"),
        ("Lupus", "Lup", "Wilk"),
        ("Lynx", "Lyn", "Ryś"),
        ("Lyra", "Lyr", "Lutnia (Lira)"),
        ("Mensa", "Men", "Góra Stołowa"),
        ("Microscopium", "Mic", "Mikroskop"),
        ("Monoceros", "Mon", "Jednorożec"),
        ("Musca", "Mus", "Mucha"),
        ("Norma", "Nor", "Węgielnica"),
        ("Octans", "Oct", "Oktant"),
        ("Ophiuchus", "Oph", "Wężownik"),
        ("Orion", "Ori", "Orion"),
        ("Pavo", "Pav", "Paw"),
        ("Pegasus", "Peg", "Pegaz"),
        ("Perseus", "Per", "Perseusz"),
        ("Phoenix", "Phe", "Feniks"),
        ("Pictor", "Pic", "Malarz"),
        ("Pisces", "Psc", "Ryby"),
        ("Piscis Austrinus", "PsA", "Ryba Południowa"),
        ("Puppis", "Pup", "Rufa"),
        ("Pyxis", "Pyx", "Kompas (Okrętowy)"),
        ("Reticulum", "Ret", "Sieć (Siatka)"),
        ("Sagitta", "Sge", "Strzała"),
        ("Sagittarius", "Sgr", "Strzelec"),
        ("Scorpius", "Sco", "Skorpion"),
        ("Sculptor", "Scl", "Rzeźbiarz"),
        ("Scutum", "Sct", "Tarcza Sobieskiego"),
        ("Serpens", "Ser", "Wąż"),
        ("Sextans", "Sex", "Sekstant"),
        ("Taurus", "Tau", "Byk"),
        ("Telescopium", "Tel", "Luneta"),
        ("Triangulum", "Tri", "Trójkąt"),
        ("Triangulum Australe", "TrA", "Trójkąt Południowy"),
        ("Tucana", "Tuc", "Tukan"),
        ("Ursa Maior", "UMa", "Wielka Niedźwiedzica"),
        ("Ursa Minor", "UMi", "Mała Niedźwiedzica"),
        ("Vela", "Vel", "Żagiel"),
        ("Virgo", "Vir", "Panna"),
        ("Volans", "Vol", "Ryba Latająca"),
        ("Vulpecula", "Vul", "Lis (Lisek)"),
    ]
    CLASS_NAMES = [constellation[0] for constellation in CONSTELLATIONS]
